# Generated by Django 5.0.2 on 2025-04-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("audio_file", models.FileField(upload_to="audio_captures/%Y/%m/%d/")),
                ("duration", models.FloatField()),
                ("sample_rate", models.IntegerField()),
                ("channels", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="AudioThreatDetection",
            fields=[
                (
                    "threatdetection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.threatdetection",
                    ),
                ),
                ("start_time", models.FloatField()),
                ("end_time", models.FloatField()),
                ("frequency_range", models.JSONField(blank=True, null=True)),
                ("transcription", models.TextField(blank=True, null=True)),
                ("audio_features", models.JSONField(default=dict)),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="audio.audiocapture",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.threatdetection",),
        ),
    ]
