# Generated by Django 5.0.2 on 2025-04-11 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisualCapture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(upload_to="visual_captures/%Y/%m/%d/")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("metadata", models.JSONField(default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.analysissession",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="VisualThreatDetection",
            fields=[
                (
                    "threatdetection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="core.threatdetection",
                    ),
                ),
                ("bounding_box", models.JSONField(blank=True, null=True)),
                ("detected_objects", models.JSONField(default=list)),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True, null=True, upload_to="threat_screenshots/%Y/%m/%d/"
                    ),
                ),
                (
                    "capture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="visual.visualcapture",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("core.threatdetection",),
        ),
    ]
